export const testimonials = [
  {
    text: "Helped me figure out if I was actually balding or not, and gave me sick recommendations and sources",
    name: "Danny7192 🇨🇦",
    date: "January 18, 2025",
    location: "Canada",
    platform: "iOS",
  },
  {
    text: "Simple to use - great overall mapping. Recommendations are clear. On a good routine now!!!",
    name: "chrxs91 🇩🇰",
    date: "November 28, 2025",
    location: "Denmark",
    platform: "iOS",
  },
  {
    text: "Tried manu apps before, but this one feels more real. The AI scan is decent, gives a clear idea about my hair condition.",
    name: "Fayisv 🇮🇳",
    date: "November 12, 2025",
    location: "India",
    platform: "iOS",
  },
  {
    text: "Im really happy with this app, it's helping me a lot, I highly recommend it. 🤩",
    name: "Douglas Machado1 🇳🇱",
    date: "November 6, 2025",
    location: "Netherlands",
    platform: "iOS",
  },
  {
    text: "I downloaded this just for fun… now I'm seriously thinking of buying shampoo for \"hope\" 😂 The AI doesn't lie bro, baldness detected 💀",
    name: "Junbh456 🇮🇳",
    date: "November 4, 2025",
    location: "India",
    platform: "iOS",
  },
  {
    text: "Awesome app to assess your hair condition and tips to maintain and remind! Very handy.",
    name: "CameronFD 🇳🇱",
    date: "November 1, 2025",
    location: "Netherlands",
    platform: "iOS",
  },
  {
    text: "App so easy to use. It immediately scanned and identified hairloss and then enabled me to track it. Would recommend. Wish i started using it sooner.",
    name: "GritDetermine 🇬🇧",
    date: "October 29, 2025",
    location: "United Kingdom",
    platform: "iOS",
  },
  {
    text: "Not that I was oblivious to the mirror, but this app was much better in visualizing where my hair loss is going.",
    name: "Dhire 🇬🇧",
    date: "October 28, 2025",
    location: "United Kingdom",
    platform: "iOS",
  },
  {
    text: "This app is really accurate which I can appreciate for the money. The products it recommended were perfect for where I'm at rn.",
    name: "Sh jeffery 🇨🇦",
    date: "November 19, 2024",
    location: "Canada",
    platform: "iOS",
  },
  {
    text: "I've been way less stressed! This app has genuinely helped me feel reassured.",
    name: "AmaanReviews 🇨🇦",
    date: "September 13, 2024",
    location: "Canada",
    platform: "iOS",
  },
  {
    text: "finnaly made me calm abour my hair.",
    name: "noresolution3354 🇵🇱",
    date: "August 26, 2024",
    location: "Poland",
    platform: "iOS",
  },
]
